version: "3.6"
services:
  frontend:
    build: ./qp4u-frontend
    volumes:
      - ./qp4u-frontend:/usr/src/app
      - usr/src/app/node_modules
    ports:
      - 3000:3000
  admin:
    build: ./qp4u-admin
    volumes:
      - ./qp4u-admin:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
  backend:
    build: ./qp4u-backend
    ports:
      - 8000:8000
    volumes:
      - "./qp4u-backend:/app"
      - ./qp4u-backend/vendor:/app/vendor
    depends_on:
      - db
  db:
    image: mariadb:10.10.5-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: albert
    volumes:
      - qp4u-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # backend:
  #   build: ./qp4u-backend
  #   ports:
  #     - 80:80

networks:
  backend:
volumes:
  qp4u-db:
